services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: apicepdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
