services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: desafiodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data